extern unsigned short int autonSelect;
extern unsigned short int Page;
extern unsigned short int Line;
extern bool AutonSelecting;
extern bool MotorChecking;
extern bool KeybindChecking;
extern bool NotesChecking;
extern void CIDisplay();
extern void AutonSelect();
extern void MotorCheck();
extern void KeybindCheck();
extern void NotesCheck();
extern void DownPressed();
extern void UpPressed();
extern void APressed();
extern void BPressed();